id: P009560
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:38:07.593415
source_metadata:
  id: bdr:W1KG14796
  title: ཕ་དམ་པ་དང་མ་ཅིག་ལབ་སྒྲོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    c6dbe67428ac440a8239991bd9dfa193:
      image_group_id: I1KG14927
      title: ''
      volume_number: 1
      total_pages: 664
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
